
from flask import Flask, render_template, request, send_file
from pptx import Presentation
import textwrap
from serpapi import GoogleSearch
import os

app = Flask(_name_)

SERPAPI_API_KEY = "YOUR_NEW_API_KEY"  # Replace with a secure API key

def fetch_google_results(topic):
    """Fetches top search results from Google using SerpApi."""
    params = {
        "q": topic,
        "api_key": SERPAPI_API_KEY,
        "num": 3
    }
    
    try:
        search = GoogleSearch(params)
        results = search.get_dict()
        
        content_list = []
        if "organic_results" in results:
            for i, result in enumerate(results["organic_results"][:3]):
                title = result.get("title", f"Topic {i+1}")
                snippet = result.get("snippet", "No description available")
                content_list.append({"title": title, "text": snippet})
        
        return content_list if content_list else [{"title": "No Data", "text": "No search results found."}]
    
    except Exception as e:
        print(f"⚠ Error fetching search results: {e}")
        return [{"title": "Error", "text": "Could not fetch search results."}]

def create_presentation(topic, output_file="static/Generated_Presentation.pptx"):
    """Creates a PowerPoint presentation and saves it."""
    prs = Presentation()
    
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = topic

    if len(slide.placeholders) > 1:
        slide.placeholders[1].text = "Generated by AI-based Presentation Generator"

    content_list = fetch_google_results(topic)

    for content in content_list:
        slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(slide_layout)
        
        title = slide.shapes.title
        body = slide.placeholders[1] if len(slide.placeholders) > 1 else None 
        
        title.text = content["title"]
        wrapped_text = "\n".join(textwrap.wrap(content["text"], width=80))
        
        if body:
            body.text = wrapped_text

    try:
        prs.save(output_file)
        print(f"✅ Presentation saved as {output_file}")
        return output_file
    except PermissionError:
        print("❌ Error: Permission denied. Close the PowerPoint file if it's open and try again.")
        return None

@app.route("/", methods=["GET", "POST"])
def index():
    if request.method == "POST":
        topic = request.form["topic"]
        pptx_file = create_presentation(topic)

        if pptx_file:
            return render_template("index.html", download_link=pptx_file)
    
    return render_template("index.html", download_link=None)

@app.route("/download_presentation")
def download_presentation():
    pptx_path = "static/Generated_Presentation.pptx"
    if os.path.exists(pptx_path):
        return send_file(pptx_path, as_attachment=True)
    return "File not found", 404

if _name_ == "_main_":
    app.run(debug=True)